### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by zachgarwood**
A complete rewrite of the API client to utilize the [Requests](http://docs.python-requests.org/) library.

Addresses issue #1.

### CODE REVIEW

**Comment by jasonabate** [comment]
Looks good to me.  What needs to be done to push this to pypi?  Once that's done @rob-barnabi please do a test install and try this out before responding to the customer that was interested.

**Comment by zachgarwood** [comment]
@jasonabate I'm not completely sure; I've never done it before. I was just going to follow [these instructions](https://packaging.python.org/en/latest/distributing/).

**Comment by jasonabate** [comment]
Sounds good.  The Pypi credentials are in Passpack, let me know if you don't have access to them.

**Comment by zachgarwood** [comment]
Here is the PyPI page: https://pypi.python.org/pypi?name=panopta-api&version=2.0.0&:action=display

**Pull request merged**
